name: Build and test

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, develop-v4, develop-v5, master ]
defaults:
  run:
    working-directory: ./src
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*

    - name: Test.Old
      run: dotnet test --configuration Release --verbosity normal Optional.OldTests

    - name: Test
      run: dotnet test --configuration Release --verbosity normal Optional.Tests