name: Build, test and publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
defaults:
  run:
    working-directory: src
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*

    - name: Build
      run: dotnet build --configuration Release

    - name: Test.Old
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal Optional.OldTests

    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal Optional.Tests

    - name: Extract version from csproj
      shell: bash
      run: |
        Version=$(grep --only-matching --perl-regex '<Version>[0-9]+(\.[0-9]+)*</Version>' Optional/Optional.csproj | grep --only-matching --perl-regex '[0-9\.]+')
        echo "Version=$Version" | tee --append "$GITHUB_ENV"
        exit $(test -n "$Version")

    - name: Pack package
      shell: bash
      run: dotnet pack Optional --configuration Release --no-build --include-symbols --nologo --output nuget

    - name: Push package
      shell: bash
      env:
        NUGETKEY: ${{ secrets.NUGETKEY }}
      run: dotnet nuget push nuget/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key "$NUGETKEY" --skip-duplicate

    - name: Create tag
      shell: bash
      run: git tag "$Version" && git push origin "$Version"
